"""CoS engine registry.

A "CoS engine" is the agentic CLI a user opens in their workspace to
orchestrate Livery — Claude Code, Codex, Pi, OpenCode, etc. Each engine
has its own convention for which file it auto-loads at startup, and
some have skill / slash-command discovery directories.

This registry lets `livery init`, `livery upgrade-workspace`, and the
onboarding flow target any registered engine without baking
engine-specific paths into the rest of the codebase. Adding a new
engine = adding an entry here.

When framework-managed content is written into an engine's convention
file, it lives between markered fences so that user content above or
below survives `livery upgrade-workspace`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


# Markers used to fence framework-managed content inside an otherwise
# user-owned convention file (CLAUDE.md, AGENTS.md, ...). The block
# between BEGIN and END is rewritten by `livery upgrade-workspace`;
# everything outside the markers is preserved verbatim.
MANAGED_BEGIN = "<!-- LIVERY-MANAGED:BEGIN — do not edit; regenerated by `livery upgrade-workspace` -->"
MANAGED_END = "<!-- LIVERY-MANAGED:END -->"


@dataclass(frozen=True, slots=True)
class CosEngine:
    """One CoS engine adapter."""

    id: str
    label: str
    invocation: str  # CLI binary the user runs to open this engine
    convention_filenames: tuple[str, ...]  # files this engine auto-loads at startup
    skills_dir: str | None = None  # relative to workspace root; None = no skill dir
    commands_dir: str | None = None  # relative to workspace root; None = no slash-command dir
    docs_url: str = ""

    @property
    def primary_convention_file(self) -> str:
        """The file `livery init` writes for this engine.

        When an engine accepts multiple filenames (e.g. Pi reads both
        AGENTS.md and CLAUDE.md), the first entry is canonical.
        """
        return self.convention_filenames[0]


# Registered engines. Order is intentional — first entries are the most
# battle-tested. Adding a new engine = appending to this dict.
COS_ENGINES: dict[str, CosEngine] = {
    "claude_code": CosEngine(
        id="claude_code",
        label="Claude Code",
        invocation="claude",
        convention_filenames=("CLAUDE.md",),
        skills_dir=".claude/skills",
        commands_dir=".claude/commands",
        docs_url="https://code.claude.com/docs/en/memory",
    ),
    "codex": CosEngine(
        id="codex",
        label="Codex",
        invocation="codex",
        convention_filenames=("AGENTS.md",),
        skills_dir=".agents/skills",
        commands_dir=None,  # Codex skills are invoked via $name; no separate slash-command dir
        docs_url="https://developers.openai.com/codex/skills",
    ),
    "pi": CosEngine(
        id="pi",
        label="Pi",
        invocation="pi",
        convention_filenames=("AGENTS.md", "CLAUDE.md"),  # Pi accepts both; AGENTS.md canonical
        skills_dir=None,
        commands_dir=None,
        docs_url="https://github.com/badlogic/pi-mono",
    ),
    "opencode": CosEngine(
        id="opencode",
        label="OpenCode",
        invocation="opencode",
        convention_filenames=("AGENTS.md",),
        skills_dir=None,
        commands_dir=None,
        docs_url="https://opencode.ai/docs/rules/",
    ),
}


# Sugar for the historical "both" alias from when claude_code and codex
# were the only options. Resolves to the two original engines so existing
# `--cos-engine both` invocations keep working.
ENGINE_ALIASES: dict[str, list[str]] = {
    "both": ["claude_code", "codex"],
}


def resolve_engines(spec: str | list[str]) -> list[str]:
    """Turn a user-supplied engine spec into a deduplicated list of engine ids.

    Accepts:
      - "claude_code"                        → ["claude_code"]
      - "claude_code,codex"                  → ["claude_code", "codex"]
      - "both"                               → ["claude_code", "codex"]
      - ["claude_code", "pi"]                → ["claude_code", "pi"]
      - "both,pi"                            → ["claude_code", "codex", "pi"]

    Raises ValueError on unknown engine ids.
    """
    raw_items: list[str] = []
    if isinstance(spec, str):
        raw_items = [s.strip() for s in spec.split(",") if s.strip()]
    else:
        raw_items = [s.strip() for s in spec if s.strip()]

    expanded: list[str] = []
    for item in raw_items:
        if item in ENGINE_ALIASES:
            expanded.extend(ENGINE_ALIASES[item])
        else:
            expanded.append(item)

    seen: set[str] = set()
    result: list[str] = []
    for engine_id in expanded:
        if engine_id not in COS_ENGINES:
            valid = ", ".join(list(COS_ENGINES.keys()) + list(ENGINE_ALIASES.keys()))
            raise ValueError(
                f"Unknown CoS engine '{engine_id}'. Valid choices: {valid}"
            )
        if engine_id not in seen:
            seen.add(engine_id)
            result.append(engine_id)

    if not result:
        raise ValueError("At least one CoS engine must be specified")
    return result


def convention_files_for(engine_ids: list[str]) -> list[str]:
    """Deduplicated list of convention filenames to scaffold for these engines.

    When two engines share a filename (codex + pi + opencode all want
    AGENTS.md), it's written once.
    """
    seen: set[str] = set()
    result: list[str] = []
    for eid in engine_ids:
        engine = COS_ENGINES[eid]
        fname = engine.primary_convention_file
        if fname not in seen:
            seen.add(fname)
            result.append(fname)
    return result


def wrap_managed(body: str) -> str:
    """Wrap framework-managed content in BEGIN/END markers."""
    return f"{MANAGED_BEGIN}\n\n{body.rstrip()}\n\n{MANAGED_END}\n"


def find_managed_block(content: str) -> tuple[int, int] | None:
    """Locate the framework-managed block in a convention file.

    Returns (start_index, end_index) of the full block including markers, or
    None if no managed block is present. Both markers must be present; if
    only one is found, returns None (treated as malformed).
    """
    begin = content.find(MANAGED_BEGIN)
    end = content.find(MANAGED_END)
    if begin == -1 or end == -1 or end < begin:
        return None
    end_full = end + len(MANAGED_END)
    return begin, end_full
