"""`livery init` — scaffold a fresh workspace in the current directory.

Creates:
  - livery.toml (workspace marker + config; declares which CoS engines)
  - agents/ (empty, with .gitkeep)
  - tickets/ (empty, with .gitkeep)
  - For each declared CoS engine:
      - its convention file (CLAUDE.md, AGENTS.md, ...) with a
        framework-managed block at the top + user-editable sections below
      - its skill / slash-command directory contents (only if the engine
        defines one)

Safe: refuses to run if livery.toml already exists in the cwd.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Literal, Optional

import frontmatter

from .cos_engines import (
    COS_ENGINES,
    convention_files_for,
    find_managed_block,
    resolve_engines,
    wrap_managed,
)


LIVERY_TOML_HEADER = """# Livery workspace config.
#
# This file marks this directory as a Livery workspace. The CLI walks up
# from your cwd looking for this file. Fields are optional with sensible
# defaults.
"""


def _render_livery_toml(
    *,
    name: str,
    description: str,
    default_runtime: str | None,
    telegram_chat_id: str | None,
    telegram_token_file: str | None,
    cos_engines: list[str],
) -> str:
    """Render a livery.toml. Unset fields are written as commented-out examples."""
    lines = [LIVERY_TOML_HEADER.rstrip(), ""]
    lines.append(f'name = "{name}"')
    lines.append(f'description = "{description}"')
    lines.append("")
    if default_runtime:
        lines.append(f'default_runtime = "{default_runtime}"')
    else:
        lines.append("# Runtime default for some subcommands. Leave unset to force explicit choice.")
        lines.append('# default_runtime = "claude_code"')
    lines.append("")
    quoted_engines = ", ".join(f'"{e}"' for e in cos_engines)
    lines.append("# CoS engines this workspace targets. Used by `livery upgrade-workspace`")
    lines.append("# to know which convention files and skill directories to manage.")
    lines.append(f"cos_engines = [{quoted_engines}]")
    lines.append("")
    lines.append("[telegram]")
    if telegram_chat_id:
        lines.append(f'chat_id = "{telegram_chat_id}"')
    else:
        lines.append('# chat_id = "-1001234567890"       # group or DM id for ticket-close pings')
    if telegram_token_file:
        lines.append(f'token_file = "{telegram_token_file}"')
    else:
        lines.append('# token_file = "~/.claude/channels/telegram/.env"  # path to bot-token .env')
    return "\n".join(lines) + "\n"


# `cos_engine` parameter on `init_workspace` accepts any registered engine
# id, the historical "both" alias, or a comma-separated combination.
# Validation lives in `cos_engines.resolve_engines`.
SUPPORTED_COS_ENGINES: tuple[str, ...] = tuple(list(COS_ENGINES.keys()) + ["both"])


# The framework-managed block written inside every convention file. This
# is what `livery upgrade-workspace` regenerates when Livery ships
# improved defaults; user content above or below the markers is preserved.
COS_MANAGED_BLOCK = """\
# Livery framework conventions

These conventions ship with Livery and apply to every workspace that uses
it. Don't edit this block — it's regenerated by `livery upgrade-workspace`
on each Livery upgrade. Add your own customizations *outside* the
LIVERY-MANAGED markers below.

## The pushback rule

Livery is an opinionated framework. The single most important opinion:
when you have ≥70% confidence the user is approaching a problem the
wrong way, say so directly *before* you do what they asked. No hedging,
no fence-sitting, no compliance theater.

This applies everywhere — CoS in conversation, agent working a dispatched
ticket, peer in a walkie-talkie. Disagreement is not disrespect. It's the
work. Complying with a request you believe is wrong delegates your
judgment back to the user, which is the failure mode this framework
exists to prevent.

In practice:

- State your position plainly. "I think this is the wrong approach. Here's
  why."
- Show your reasoning. Be concrete about what you'd do differently.
- Stop. Let the user respond. Don't pre-bracket disagreement with "but
  ultimately it's your call" — that's hedging dressed up as deference.
- If the user still wants the original approach after hearing your case,
  do it. Pushback is a forcing function for informed decisions, not veto
  power.

The 70% threshold is high on purpose. It asks for confidence, not
contrarianism. When it's met, surface the disagreement. The user has
explicitly asked for this — they want the senior-collaborator version of
you, not the intern-compliance version.

## Operational defaults

- On ticket close, ping Telegram if `livery.toml` configures it.
- Every ticket mutation should be followed by a git commit.
- Plain language. Tech-savvy users may not be programmers; skip jargon.

## Discoverability

- When you are unsure what Livery can do from the current directory, run
  `livery next`.
- When you need the full feature menu, run `livery capabilities`.
- When acting programmatically or advising another agent, prefer structured
  output: `livery next --format json` and `livery capabilities --format json`.
- Treat those commands as live framework truth. Do not rely on stale memory
  or guess at hidden options.

## Livery loop, in one paragraph

You file tickets (`livery ticket new`), the CoS handles them directly or
prepares dispatch (`livery dispatch prep <ticket> --worktree`) to a hired
agent, the agent runs and reports back via a `=== DISPATCH_SUMMARY ===`
block, you (or the CoS) close the ticket (`livery ticket close <id>
--summary`). Worktrees keep agents from stepping on your in-progress work.
"""

# The user-editable section that appears *below* the managed block in a
# fresh convention file. Users own this section forever — Livery never
# touches it after init.
COS_USER_TEMPLATE = """\
# {name}

## About

{description}

## Agents

_No agents hired yet. Run `livery hire <role>` to scaffold one._

## Custom conventions for the CoS (you)

_Add workspace-specific rules here. Examples: domain conventions, paired
repos, style preferences, escalation paths. Anything you write here is
yours — Livery's `upgrade-workspace` command will not touch this section._
"""

TICKET_SLASH = """---
description: Create a new Livery ticket
argument-hint: [title or brief description]
livery: managed
---

Help the user create a new Livery ticket.

If `$ARGUMENTS` is present, treat it as the starting title or description.

Steps:
1. Gather any missing details conversationally:
   - **title** — one-line, imperative ("Add login timeout", not "Login bug")
   - **assignee** — agent id from `agents/<id>/`, `cos` for the CoS session, or leave blank
   - **description** — one paragraph stating the goal
   - **context** (optional) — links, constraints, prior decisions
2. Run `livery ticket new --title "..." --assignee <id|cos> --description "..." [--context "..."]`.
3. Show the user the created file path and ticket id.
"""

NEW_TICKET_SKILL = """---
name: new-ticket
description: Create a new Livery ticket to track work or delegate to an agent. Use when the user says "create a ticket", "new ticket", "file a ticket", invokes `/ticket`, or describes a unit of work that should be formalized.
livery: managed
---

# Create a Livery ticket

Livery tracks work as markdown tickets in `tickets/<YYYY-MM-DD>-<NNN>-<slug>.md`. Each ticket has frontmatter (id, title, assignee, status, timestamps) and body sections (`## Description`, optional `## Context`, `## Thread`).

## When to invoke

- User types `/ticket` or asks to "create/file/open a ticket"
- User describes a unit of work that belongs in the backlog or should be delegated to another agent

## Fields

- **title** — one-line, imperative
- **assignee** — agent id, `cos` for the CoS session, or blank
- **description** — one paragraph stating the goal
- **context** (optional) — links, constraints, prior decisions

## Steps

1. Gather missing fields conversationally.
2. Run `livery ticket new --title "..." --assignee <id|cos|null> --description "..." [--context "..."]`.
3. Show the created path.
"""


WALKIE_SLASH = """---
description: Start or continue a Walkie-Talkie debate with another AI session
argument-hint: [topic] [--with peer-id]
livery: managed
---

Run a Walkie-Talkie session — a turn-based, append-only debate between
this AI session and a peer in another harness (e.g. Codex while you're
in Claude Code, or vice versa).

If `$ARGUMENTS` includes a topic and `--with`, run:
  `livery walkie new <topic> --with <peer> --as <self>`
where `<self>` is the engine you're running in (`claude-code`, `codex`,
`pi`, `opencode`).

If the user is asking about an existing walkie, run `livery walkie list`
first and then `livery walkie show <topic>` for the relevant one.

Then participate in the walkie by appending turns to the file. The file
includes the full protocol at the bottom — read it before each turn and
follow it strictly.
"""


WALKIE_SKILL = """---
name: walkie-talkie
description: Participate in a turn-based async debate with another AI session via a shared markdown file. Use when starting or continuing a Walkie-Talkie, or when the user says "let's walkie-talkie with codex/claude/etc on X".
livery: managed
---

# Walkie-Talkie

Walkie-Talkie is a Livery protocol for two AI sessions in different
harnesses (Claude Code, Codex, Pi, OpenCode) to converge on a hard
decision by debating in a shared file.

## When to invoke

- User asks to "walkie-talkie with <peer> about <topic>"
- User invokes `/walkie`
- The user is already in an active walkie (file under
  `<workspace>/walkie-talkie/`) and is asking you to take a turn

## Starting a new walkie

Run `livery walkie new <topic> --with <peer-id> --as <your-engine>`. Use
your harness's engine id for `--as` (`claude-code` for Claude Code,
`codex` for Codex). Tell the user the file path so they can hand it to
the peer harness.

After the file exists, take Turn 1 yourself: read the file (the protocol
section is at the bottom — read it carefully), then append your opening
turn following the format `## Turn 1 — <your-id> — <ISO8601 ts>`.

## Continuing an existing walkie

1. **Read the entire file from the top.** Don't reply to one turn out
   of context.
2. Find the highest `Turn N` header. The next turn is `N+1`.
3. Check whether the previous turn was yours — if so, you're waiting on
   the peer; don't double-append. Tell the user.
4. Otherwise, append your turn at the bottom (above the protocol
   section), following the header format precisely.

## Protocol non-negotiables

The protocol lives in the walkie file itself, but the load-bearing
rules are:

- **Append only.** Never prepend or rewrite earlier turns.
- **Turn header format:** `## Turn N — <your-id> — <ISO8601-UTC ts>`.
  Mismatched headers will desync parsing.
- **Push back hard.** If you disagree with the peer's reasoning, say
  so directly with reasoning — don't capitulate.
- **Sign to converge.** When both you and the peer have agreed,
  append `SIGNED: <your-id> @ <ts>` inside your turn. Both peers must
  sign for the walkie to lock.

## Watching for the peer

The peer takes their turn asynchronously. If the user wants you to wait
on a reply, poll the file (re-read it) periodically — every ~60s when
actively engaged, ~15s right after you append. Stop when you see the
turn count has incremented or the user redirects.
"""


@dataclass(slots=True, frozen=True)
class SkillCollisionResolution:
    """Returned by the skill-collision callback to tell `init_workspace`
    what to do with a pre-existing user-written skill/command file.

    - `action = "skip"`: leave the user's file in place, do NOT install
      Livery's version. Result: the user keeps their thing; Livery's
      slash command / skill is not available in this workspace.
    - `action = "overwrite"`: replace the user's file with Livery's.
      Destructive — only use when the user explicitly asks for it.
    - `action = "rename"`: rename the user's existing skill or command
      to a new functional name (so it stays usable as that name), then
      install Livery's at the original path. `new_name` is required;
      it's the new identifier the user wants their skill/command to
      live under.
    """
    action: Literal["skip", "overwrite", "rename"]
    new_name: str | None = None

    @classmethod
    def skip(cls) -> "SkillCollisionResolution":
        return cls(action="skip")

    @classmethod
    def overwrite(cls) -> "SkillCollisionResolution":
        return cls(action="overwrite")

    @classmethod
    def rename(cls, new_name: str) -> "SkillCollisionResolution":
        if not new_name:
            raise ValueError("rename requires a non-empty new_name")
        return cls(action="rename", new_name=new_name)


SkillCollisionCallback = Callable[[Path], SkillCollisionResolution]
"""Called by `init_workspace` when it finds a non-Livery-managed file at a
skill or command target path. Receives the colliding path; returns the
resolution. Default behavior (when callback is None) is `skip`."""


def _is_livery_managed_skill(path: Path) -> bool:
    """True if the markdown file at `path` has `livery: managed` in its frontmatter.

    Used to distinguish Livery-shipped skill/command files (safe to overwrite
    or no-op-replace) from user-written files at the same path (must not be
    silently clobbered).
    """
    try:
        post = frontmatter.load(path)
    except Exception:
        return False
    return post.get("livery") == "managed"


def _is_skill_path(path: Path) -> bool:
    """A 'skill' is `<...>/skills/<skill-name>/SKILL.md`. A 'command' is
    `<...>/commands/<command-name>.md`. Different rename semantics."""
    return path.name == "SKILL.md" and path.parent.parent.name == "skills"


def _rename_user_skill(skill_md_path: Path, new_name: str) -> Path:
    """Rename a user's existing skill to `new_name` so it stays functional.

    Skills live in directories: `.../skills/<name>/SKILL.md`. To rename:
    - Rename the parent directory (`<name>` → `<new_name>`)
    - Update the SKILL.md frontmatter `name` field to match

    Returns the new SKILL.md path. Raises FileExistsError if a directory
    at the new name already exists.
    """
    from .paths_safety import sanitize_path_component
    safe_new = sanitize_path_component(new_name, fallback="renamed-skill")

    skill_dir = skill_md_path.parent
    parent_dir = skill_dir.parent  # the `.../skills/` dir
    new_dir = parent_dir / safe_new

    if new_dir.exists():
        raise FileExistsError(
            f"can't rename {skill_dir} to {new_dir}: target already exists"
        )

    skill_dir.rename(new_dir)

    # Update the frontmatter `name` field so Claude Code / Codex see the new id.
    new_skill_md = new_dir / "SKILL.md"
    try:
        post = frontmatter.load(new_skill_md)
        post["name"] = safe_new
        new_skill_md.write_text(frontmatter.dumps(post) + "\n")
    except Exception:
        # If the user's skill had unparseable frontmatter, leave it alone —
        # the rename of the directory still gives them a working location.
        pass

    return new_skill_md


def _rename_user_command(command_md_path: Path, new_name: str) -> Path:
    """Rename a user's existing slash command to `new_name`.

    Commands live as single files: `.../commands/<name>.md`. To rename,
    we just move the file to `.../commands/<new_name>.md`.

    Returns the new path. Raises FileExistsError on collision.
    """
    from .paths_safety import sanitize_path_component
    safe_new = sanitize_path_component(new_name, fallback="renamed-command")

    parent = command_md_path.parent
    new_path = parent / f"{safe_new}.md"

    if new_path.exists():
        raise FileExistsError(
            f"can't rename {command_md_path} to {new_path}: target already exists"
        )

    command_md_path.rename(new_path)
    return new_path


@dataclass(slots=True)
class InitResult:
    """Returned by `init_workspace`. Created replaces the old return type
    (a list of paths) with a richer structure that callers can present to
    users — which files were written, which were left alone, which collided."""

    created: list[Path] = field(default_factory=list)
    """Files Livery wrote (or rewrote)."""

    appended: list[Path] = field(default_factory=list)
    """Pre-existing convention files where Livery wrote a fresh template and
    appended the old content. The user has both their old content and the
    new framework block."""

    skipped: list[tuple[Path, str]] = field(default_factory=list)
    """Pre-existing skill/command files Livery did NOT install over.
    Each entry is (path, reason). User-written files where the collision
    callback returned `skip` end up here."""

    backed_up: list[tuple[Path, Path]] = field(default_factory=list)
    """User-written skill/command files that were renamed to `.bak`
    before Livery's version was installed. Each entry is (original, backup)."""


def init_workspace(
    target: Path,
    name: str,
    description: str = "",
    default_runtime: str | None = None,
    telegram_chat_id: str | None = None,
    telegram_token_file: str | None = None,
    cos_engine: str | list[str] = "both",
    overwrite: bool = False,
    skill_collision_callback: SkillCollisionCallback | None = None,
) -> InitResult:
    """Scaffold a new workspace at `target`. Returns an `InitResult`.

    `cos_engine` controls which CoS engines this workspace targets. Accepts:
      - a single engine id ("claude_code", "codex", "pi", "opencode", ...)
      - "both" (back-compat alias for ["claude_code", "codex"])
      - a comma-separated string ("claude_code,pi")
      - a list of engine ids

    Behavior on a populated directory:

    - `livery.toml`: refuses unless `overwrite=True`. (Same as before.)
    - `CLAUDE.md` / `AGENTS.md`: writes the fresh template and appends the
      pre-existing file content at the bottom. Any pre-existing
      LIVERY-MANAGED block in the old content is stripped to avoid
      duplication. Result: managed block at top + user-editable scaffold +
      whatever the user had before.
    - Skill / command files (`.claude/...`, `.agents/skills/...`): if
      Livery-managed (frontmatter has `livery: managed`), no-op replace
      with current shipped version. If NOT Livery-managed, calls
      `skill_collision_callback(path)`; default is `skip` and the user's
      file is left alone. CLI wraps this with an interactive prompt.
    """
    engine_ids = resolve_engines(cos_engine)
    callback: SkillCollisionCallback = skill_collision_callback or (lambda _p: SkillCollisionResolution.skip())

    target = target.resolve()
    target.mkdir(parents=True, exist_ok=True)

    marker = target / "livery.toml"
    if marker.exists() and not overwrite:
        raise FileExistsError(
            f"{marker} already exists. Refusing to overwrite. "
            "Pass overwrite=True to force."
        )

    result = InitResult()

    def _write_fresh(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        result.created.append(path)

    _write_fresh(marker, _render_livery_toml(
        name=name,
        description=description,
        default_runtime=default_runtime,
        telegram_chat_id=telegram_chat_id,
        telegram_token_file=telegram_token_file,
        cos_engines=engine_ids,
    ))

    # Convention files: write fresh template; if a file already existed,
    # append its content (minus any old managed block) at the bottom.
    user_body = COS_USER_TEMPLATE.format(
        name=name,
        description=description or "(Describe your workspace here.)",
    )
    fresh_template = wrap_managed(COS_MANAGED_BLOCK) + "\n" + user_body

    for filename in convention_files_for(engine_ids):
        path = target / filename
        if not path.exists():
            _write_fresh(path, fresh_template)
            continue

        # File exists — preserve its content by appending below the fresh template.
        # Strip any pre-existing LIVERY-MANAGED block so we don't duplicate it.
        old = path.read_text()
        block_range = find_managed_block(old)
        if block_range is not None:
            start, end = block_range
            old_user_content = (old[:start] + old[end:]).strip()
        else:
            old_user_content = old.strip()

        if old_user_content:
            divider = (
                f"\n\n## Carried over from previous {filename}\n\n"
                "_The content below was in this file before `livery init` ran. "
                "Reorganize as you see fit; Livery won't touch it again._\n\n"
            )
            new_content = fresh_template.rstrip() + divider + old_user_content + "\n"
        else:
            new_content = fresh_template
        path.write_text(new_content)
        result.appended.append(path)

    _write_fresh(target / "agents" / ".gitkeep", "")
    _write_fresh(target / "tickets" / ".gitkeep", "")

    # Engine-specific skill / command assets. For each target path:
    # - if missing → write Livery's
    # - if present and Livery-managed → no-op overwrite (refresh content)
    # - if present and NOT Livery-managed → callback decides rename vs skip
    skill_targets_seen: set[str] = set()

    def _install_skill_file(path: Path, content: str) -> None:
        if str(path) in skill_targets_seen:
            return
        skill_targets_seen.add(str(path))

        if not path.exists():
            _write_fresh(path, content)
            return

        if _is_livery_managed_skill(path):
            # It's ours. Refresh in place.
            path.write_text(content)
            result.created.append(path)
            return

        # User-written file at our target path. Ask the callback what to do.
        decision = callback(path)

        if decision.action == "skip":
            result.skipped.append((
                path,
                "user-written skill/command at Livery target path; left in place. "
                "Livery's version was NOT installed.",
            ))
            return

        if decision.action == "overwrite":
            path.write_text(content)
            result.created.append(path)
            return

        if decision.action == "rename":
            assert decision.new_name, "rename resolution requires new_name"
            try:
                if _is_skill_path(path):
                    new_path = _rename_user_skill(path, decision.new_name)
                else:
                    new_path = _rename_user_command(path, decision.new_name)
            except FileExistsError as e:
                # Bubble up to the caller — CLI can re-prompt for a different name.
                raise FileExistsError(
                    f"can't rename existing skill/command at {path}: {e}"
                ) from e
            result.backed_up.append((path, new_path))
            _write_fresh(path, content)
            return

        raise ValueError(f"unknown collision action: {decision.action!r}")

    for eid in engine_ids:
        engine = COS_ENGINES[eid]
        if engine.commands_dir:
            _install_skill_file(target / engine.commands_dir / "ticket.md", TICKET_SLASH)
            _install_skill_file(target / engine.commands_dir / "walkie.md", WALKIE_SLASH)
        if engine.skills_dir:
            _install_skill_file(target / engine.skills_dir / "new-ticket" / "SKILL.md", NEW_TICKET_SKILL)
            _install_skill_file(target / engine.skills_dir / "walkie-talkie" / "SKILL.md", WALKIE_SKILL)

    return result
