"""`livery init` — scaffold a fresh workspace in the current directory.

Creates:
  - livery.toml (workspace marker + config; declares which CoS engines)
  - agents/ (empty, with .gitkeep)
  - tickets/ (empty, with .gitkeep)
  - For each declared CoS engine:
      - its convention file (CLAUDE.md, AGENTS.md, ...) with a
        framework-managed block at the top + user-editable sections below
      - its skill / slash-command directory contents (only if the engine
        defines one)

Safe: refuses to run if livery.toml already exists in the cwd.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from .cos_engines import (
    COS_ENGINES,
    convention_files_for,
    resolve_engines,
    wrap_managed,
)


LIVERY_TOML_HEADER = """# Livery workspace config.
#
# This file marks this directory as a Livery workspace. The CLI walks up
# from your cwd looking for this file. Fields are optional with sensible
# defaults.
"""


def _render_livery_toml(
    *,
    name: str,
    description: str,
    default_runtime: str | None,
    telegram_chat_id: str | None,
    telegram_token_file: str | None,
    cos_engines: list[str],
) -> str:
    """Render a livery.toml. Unset fields are written as commented-out examples."""
    lines = [LIVERY_TOML_HEADER.rstrip(), ""]
    lines.append(f'name = "{name}"')
    lines.append(f'description = "{description}"')
    lines.append("")
    if default_runtime:
        lines.append(f'default_runtime = "{default_runtime}"')
    else:
        lines.append("# Runtime default for some subcommands. Leave unset to force explicit choice.")
        lines.append('# default_runtime = "claude_code"')
    lines.append("")
    quoted_engines = ", ".join(f'"{e}"' for e in cos_engines)
    lines.append("# CoS engines this workspace targets. Used by `livery upgrade-workspace`")
    lines.append("# to know which convention files and skill directories to manage.")
    lines.append(f"cos_engines = [{quoted_engines}]")
    lines.append("")
    lines.append("[telegram]")
    if telegram_chat_id:
        lines.append(f'chat_id = "{telegram_chat_id}"')
    else:
        lines.append('# chat_id = "-1001234567890"       # group or DM id for ticket-close pings')
    if telegram_token_file:
        lines.append(f'token_file = "{telegram_token_file}"')
    else:
        lines.append('# token_file = "~/.claude/channels/telegram/.env"  # path to bot-token .env')
    return "\n".join(lines) + "\n"


# `cos_engine` parameter on `init_workspace` accepts any registered engine
# id, the historical "both" alias, or a comma-separated combination.
# Validation lives in `cos_engines.resolve_engines`.
SUPPORTED_COS_ENGINES: tuple[str, ...] = tuple(list(COS_ENGINES.keys()) + ["both"])


# The framework-managed block written inside every convention file. This
# is what `livery upgrade-workspace` regenerates when Livery ships
# improved defaults; user content above or below the markers is preserved.
COS_MANAGED_BLOCK = """\
# Livery framework conventions

These conventions ship with Livery and apply to every workspace that uses
it. Don't edit this block — it's regenerated by `livery upgrade-workspace`
on each Livery upgrade. Add your own customizations *outside* the
LIVERY-MANAGED markers below.

## How the CoS should behave

- Push back hard when you think the user may be wrong. ≥70% confidence to
  disagree, don't hedge, show your reasoning.
- On ticket close, ping Telegram if `livery.toml` configures it.
- Every ticket mutation should be followed by a git commit.
- Plain language. Tech-savvy users may not be programmers; skip jargon.

## Livery loop, in one paragraph

You file tickets (`livery ticket new`), the CoS handles them directly or
prepares dispatch (`livery dispatch prep <ticket> --worktree`) to a hired
agent, the agent runs and reports back via a `=== DISPATCH_SUMMARY ===`
block, you (or the CoS) close the ticket (`livery ticket close <id>
--summary`). Worktrees keep agents from stepping on your in-progress work.
"""

# The user-editable section that appears *below* the managed block in a
# fresh convention file. Users own this section forever — Livery never
# touches it after init.
COS_USER_TEMPLATE = """\
# {name}

## About

{description}

## Agents

_No agents hired yet. Run `livery hire <role>` to scaffold one._

## Custom conventions for the CoS (you)

_Add workspace-specific rules here. Examples: domain conventions, paired
repos, style preferences, escalation paths. Anything you write here is
yours — Livery's `upgrade-workspace` command will not touch this section._
"""

TICKET_SLASH = """---
description: Create a new Livery ticket
argument-hint: [title or brief description]
---

Help the user create a new Livery ticket.

If `$ARGUMENTS` is present, treat it as the starting title or description.

Steps:
1. Gather any missing details conversationally:
   - **title** — one-line, imperative ("Add login timeout", not "Login bug")
   - **assignee** — agent id from `agents/<id>/`, `cos` for the CoS session, or leave blank
   - **description** — one paragraph stating the goal
   - **context** (optional) — links, constraints, prior decisions
2. Run `livery ticket new --title "..." --assignee <id|cos> --description "..." [--context "..."]`.
3. Show the user the created file path and ticket id.
"""

NEW_TICKET_SKILL = """---
name: new-ticket
description: Create a new Livery ticket to track work or delegate to an agent. Use when the user says "create a ticket", "new ticket", "file a ticket", invokes `/ticket`, or describes a unit of work that should be formalized.
---

# Create a Livery ticket

Livery tracks work as markdown tickets in `tickets/<YYYY-MM-DD>-<NNN>-<slug>.md`. Each ticket has frontmatter (id, title, assignee, status, timestamps) and body sections (`## Description`, optional `## Context`, `## Thread`).

## When to invoke

- User types `/ticket` or asks to "create/file/open a ticket"
- User describes a unit of work that belongs in the backlog or should be delegated to another agent

## Fields

- **title** — one-line, imperative
- **assignee** — agent id, `cos` for the CoS session, or blank
- **description** — one paragraph stating the goal
- **context** (optional) — links, constraints, prior decisions

## Steps

1. Gather missing fields conversationally.
2. Run `livery ticket new --title "..." --assignee <id|cos|null> --description "..." [--context "..."]`.
3. Show the created path.
"""


def init_workspace(
    target: Path,
    name: str,
    description: str = "",
    default_runtime: str | None = None,
    telegram_chat_id: str | None = None,
    telegram_token_file: str | None = None,
    cos_engine: str | list[str] = "both",
    overwrite: bool = False,
) -> list[Path]:
    """Scaffold a new workspace at `target`. Returns the list of files created.

    `cos_engine` controls which CoS engines this workspace targets. Accepts:
      - a single engine id ("claude_code", "codex", "pi", "opencode", ...)
      - "both" (back-compat alias for ["claude_code", "codex"])
      - a comma-separated string ("claude_code,pi")
      - a list of engine ids
    """
    engine_ids = resolve_engines(cos_engine)

    target = target.resolve()
    target.mkdir(parents=True, exist_ok=True)

    marker = target / "livery.toml"
    if marker.exists() and not overwrite:
        raise FileExistsError(
            f"{marker} already exists. Refusing to overwrite. "
            "Pass overwrite=True to force."
        )

    created: list[Path] = []

    def _write(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        created.append(path)

    _write(marker, _render_livery_toml(
        name=name,
        description=description,
        default_runtime=default_runtime,
        telegram_chat_id=telegram_chat_id,
        telegram_token_file=telegram_token_file,
        cos_engines=engine_ids,
    ))

    # Convention files: write each unique filename once, with a
    # framework-managed block at top (regenerable on upgrade) and a
    # user-editable section below (never touched after init).
    user_body = COS_USER_TEMPLATE.format(
        name=name,
        description=description or "(Describe your workspace here.)",
    )
    full_body = wrap_managed(COS_MANAGED_BLOCK) + "\n" + user_body
    for filename in convention_files_for(engine_ids):
        _write(target / filename, full_body)

    _write(target / "agents" / ".gitkeep", "")
    _write(target / "tickets" / ".gitkeep", "")

    # Engine-specific skill / command assets. Each engine declares its own
    # discovery directories; we scaffold the same skill content into each.
    skill_dirs_seen: set[str] = set()
    for eid in engine_ids:
        engine = COS_ENGINES[eid]
        if engine.commands_dir:
            cmd_path = target / engine.commands_dir / "ticket.md"
            if str(cmd_path) not in skill_dirs_seen:
                _write(cmd_path, TICKET_SLASH)
                skill_dirs_seen.add(str(cmd_path))
        if engine.skills_dir:
            skill_path = target / engine.skills_dir / "new-ticket" / "SKILL.md"
            if str(skill_path) not in skill_dirs_seen:
                _write(skill_path, NEW_TICKET_SKILL)
                skill_dirs_seen.add(str(skill_path))

    return created
